// Mock data for restaurant management system
export const mockUsers = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@restaurant.com",
    password: "admin123",
    role: "ADMIN" as const,
    isActive: true,
  },
  {
    id: "2",
    name: "John Cashier",
    email: "cashier@restaurant.com",
    password: "cashier123",
    role: "CASHIER" as const,
    isActive: true,
  },
  {
    id: "3",
    name: "Sarah Waiter",
    email: "waiter@restaurant.com",
    password: "waiter123",
    role: "WAITER" as const,
    isActive: true,
  },
  {
    id: "4",
    name: "Mike Kitchen",
    email: "kitchen@restaurant.com",
    password: "kitchen123",
    role: "KITCHEN" as const,
    isActive: true,
  },
]

export const mockCategories = [
  { id: "1", name: "Appetizers", imageUrl: "/assorted-appetizers.png" },
  { id: "2", name: "Main Course", imageUrl: "/main-course-selection.png" },
  { id: "3", name: "Desserts", imageUrl: "/assorted-desserts.png" },
  { id: "4", name: "Beverages", imageUrl: "/assorted-beverages.png" },
]

export const mockMenuItems = [
  {
    id: "1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with parmesan and croutons",
    price: 8.99,
    imageUrl: "/caesar-salad.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "1",
  },
  {
    id: "2",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter",
    price: 5.99,
    imageUrl: "/garlic-bread.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "1",
  },
  {
    id: "3",
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon with herbs",
    price: 24.99,
    imageUrl: "/grilled-salmon-plate.png",
    isAvailable: true,
    isVeg: false,
    categoryId: "2",
  },
  {
    id: "4",
    name: "Beef Steak",
    description: "Prime beef cooked to perfection",
    price: 29.99,
    imageUrl: "/juicy-beef-steak.png",
    isAvailable: true,
    isVeg: false,
    categoryId: "2",
  },
  {
    id: "5",
    name: "Pasta Primavera",
    description: "Fresh vegetables with penne pasta",
    price: 16.99,
    imageUrl: "/colorful-pasta-arrangement.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "2",
  },
  {
    id: "6",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center",
    price: 7.99,
    imageUrl: "/chocolate-lava-cake.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "3",
  },
  {
    id: "7",
    name: "Tiramisu",
    description: "Classic Italian dessert",
    price: 8.99,
    imageUrl: "/classic-tiramisu.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "3",
  },
  {
    id: "8",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 4.99,
    imageUrl: "/glass-of-orange-juice.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "4",
  },
  {
    id: "9",
    name: "Espresso",
    description: "Strong Italian coffee",
    price: 3.99,
    imageUrl: "/espresso-shot.png",
    isAvailable: true,
    isVeg: true,
    categoryId: "4",
  },
]

export const mockTables = [
  { id: "1", name: "Table 1", seats: 4, status: "AVAILABLE" as const, assignedTo: null },
  { id: "2", name: "Table 2", seats: 2, status: "OCCUPIED" as const, assignedTo: "3" },
  { id: "3", name: "Table 3", seats: 6, status: "RESERVED" as const, assignedTo: "3" },
  { id: "4", name: "Table 4", seats: 4, status: "AVAILABLE" as const, assignedTo: null },
  { id: "5", name: "Table 5", seats: 2, status: "OCCUPIED" as const, assignedTo: "3" },
  { id: "6", name: "Table 6", seats: 8, status: "NEEDS_CLEANING" as const, assignedTo: null },
  { id: "7", name: "Table 7", seats: 4, status: "AVAILABLE" as const, assignedTo: null },
  { id: "8", name: "Table 8", seats: 2, status: "AVAILABLE" as const, assignedTo: null },
]

export const mockOrders = [
  {
    id: "1",
    tableId: "2",
    status: "preparing" as const,
    placedBy: "Guest 1",
    notes: "No onions please",
    createdAt: new Date("2025-01-15T12:30:00"),
    createdBy: "3",
    items: [
      { menuItemId: "3", name: "Grilled Salmon", quantity: 2, price: 24.99 },
      { menuItemId: "8", name: "Fresh Orange Juice", quantity: 2, price: 4.99 },
    ],
    total: 59.96,
  },
  {
    id: "2",
    tableId: "5",
    status: "ready" as const,
    placedBy: "Guest 2",
    notes: "",
    createdAt: new Date("2025-01-15T13:00:00"),
    createdBy: "3",
    items: [
      { menuItemId: "4", name: "Beef Steak", quantity: 1, price: 29.99 },
      { menuItemId: "1", name: "Caesar Salad", quantity: 1, price: 8.99 },
    ],
    total: 38.98,
  },
  {
    id: "3",
    tableId: "2",
    status: "pending" as const,
    placedBy: "Guest 3",
    notes: "Birthday celebration",
    createdAt: new Date("2025-01-15T13:15:00"),
    createdBy: "3",
    items: [
      { menuItemId: "5", name: "Pasta Primavera", quantity: 3, price: 16.99 },
      { menuItemId: "6", name: "Chocolate Lava Cake", quantity: 3, price: 7.99 },
    ],
    total: 74.94,
  },
]

export const mockReservations = [
  {
    id: "1",
    tableId: "3",
    guestName: "John Smith",
    guestPhone: "+1-555-0123",
    guests: 4,
    status: "ACTIVE" as const,
    reservedAt: new Date("2025-01-15T19:00:00"),
    reservedUntil: new Date("2025-01-15T21:00:00"),
    durationMin: 120,
  },
  {
    id: "2",
    tableId: "6",
    guestName: "Emma Wilson",
    guestPhone: "+1-555-0456",
    guests: 8,
    status: "ACTIVE" as const,
    reservedAt: new Date("2025-01-15T20:00:00"),
    reservedUntil: new Date("2025-01-15T22:00:00"),
    durationMin: 120,
  },
]

export const mockBills = [
  {
    id: "1",
    orderId: "2",
    generatedAt: new Date("2025-01-15T13:45:00"),
    generatedBy: "2",
    subTotal: 38.98,
    discountValue: 5,
    discountType: "PERCENTAGE" as const,
    serviceCharge: 2.0,
    taxPct: 13,
    taxAmount: 4.68,
    grandTotal: 43.61,
    paymentMode: "CARD" as const,
    isPaid: true,
    paidAt: new Date("2025-01-15T13:46:00"),
  },
]

export const mockSurplusItems = [
  {
    id: "1",
    menuItemId: "7",
    markedBy: "1",
    surplusAt: new Date(),
    surplusUntil: new Date(Date.now() + 2 * 60 * 60 * 1000),
    discountPct: 30,
    note: "Flash sale - last 5 items",
  },
]